/*
 * This file is generated by jOOQ.
 */
package com.schema.tables.records;


import com.schema.tables.Agency;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgencyRecord extends UpdatableRecordImpl<AgencyRecord> implements Record6<UInteger, String, String, String, String, String> {

    private static final long serialVersionUID = -885062856;

    /**
     * Setter for <code>gtfs.agency.key</code>.
     */
    public void setKey(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>gtfs.agency.key</code>.
     */
    public UInteger getKey() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>gtfs.agency.agency_id</code>.
     */
    public void setAgencyId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gtfs.agency.agency_id</code>.
     */
    public String getAgencyId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gtfs.agency.agency_name</code>.
     */
    public void setAgencyName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gtfs.agency.agency_name</code>.
     */
    public String getAgencyName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gtfs.agency.agency_url</code>.
     */
    public void setAgencyUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gtfs.agency.agency_url</code>.
     */
    public String getAgencyUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gtfs.agency.agency_timezone</code>.
     */
    public void setAgencyTimezone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gtfs.agency.agency_timezone</code>.
     */
    public String getAgencyTimezone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gtfs.agency.feed_version</code>.
     */
    public void setFeedVersion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gtfs.agency.feed_version</code>.
     */
    public String getFeedVersion() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Agency.AGENCY.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Agency.AGENCY.AGENCY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Agency.AGENCY.AGENCY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Agency.AGENCY.AGENCY_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Agency.AGENCY.AGENCY_TIMEZONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Agency.AGENCY.FEED_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAgencyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAgencyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAgencyUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAgencyTimezone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFeedVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAgencyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAgencyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAgencyUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAgencyTimezone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFeedVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgencyRecord value1(UInteger value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgencyRecord value2(String value) {
        setAgencyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgencyRecord value3(String value) {
        setAgencyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgencyRecord value4(String value) {
        setAgencyUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgencyRecord value5(String value) {
        setAgencyTimezone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgencyRecord value6(String value) {
        setFeedVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AgencyRecord values(UInteger value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgencyRecord
     */
    public AgencyRecord() {
        super(Agency.AGENCY);
    }

    /**
     * Create a detached, initialised AgencyRecord
     */
    public AgencyRecord(UInteger key, String agencyId, String agencyName, String agencyUrl, String agencyTimezone, String feedVersion) {
        super(Agency.AGENCY);

        set(0, key);
        set(1, agencyId);
        set(2, agencyName);
        set(3, agencyUrl);
        set(4, agencyTimezone);
        set(5, feedVersion);
    }
}
