/*
 * This file is generated by jOOQ.
 */
package com.schema.tables.records;


import com.schema.tables.FeedVersion;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeedVersionRecord extends UpdatableRecordImpl<FeedVersionRecord> implements Record8<String, String, ULong, ULong, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1560093179;

    /**
     * Setter for <code>gtfs.feed_version.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gtfs.feed_version.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gtfs.feed_version.feed</code>.
     */
    public void setFeed(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gtfs.feed_version.feed</code>.
     */
    public String getFeed() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gtfs.feed_version.timestamp</code>.
     */
    public void setTimestamp(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>gtfs.feed_version.timestamp</code>.
     */
    public ULong getTimestamp() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>gtfs.feed_version.size</code>.
     */
    public void setSize(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>gtfs.feed_version.size</code>.
     */
    public ULong getSize() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>gtfs.feed_version.url</code>.
     */
    public void setUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gtfs.feed_version.url</code>.
     */
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gtfs.feed_version.start</code>.
     */
    public void setStart(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gtfs.feed_version.start</code>.
     */
    public String getStart() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gtfs.feed_version.finish</code>.
     */
    public void setFinish(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gtfs.feed_version.finish</code>.
     */
    public String getFinish() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gtfs.feed_version.inserted</code>.
     */
    public void setInserted(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>gtfs.feed_version.inserted</code>.
     */
    public Timestamp getInserted() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, ULong, ULong, String, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, ULong, ULong, String, String, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return FeedVersion.FEED_VERSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FeedVersion.FEED_VERSION.FEED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return FeedVersion.FEED_VERSION.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field4() {
        return FeedVersion.FEED_VERSION.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FeedVersion.FEED_VERSION.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FeedVersion.FEED_VERSION.START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return FeedVersion.FEED_VERSION.FINISH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return FeedVersion.FEED_VERSION.INSERTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component3() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component4() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFinish();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getInserted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value4() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFinish();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getInserted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedVersionRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedVersionRecord value2(String value) {
        setFeed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedVersionRecord value3(ULong value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedVersionRecord value4(ULong value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedVersionRecord value5(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedVersionRecord value6(String value) {
        setStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedVersionRecord value7(String value) {
        setFinish(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedVersionRecord value8(Timestamp value) {
        setInserted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedVersionRecord values(String value1, String value2, ULong value3, ULong value4, String value5, String value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeedVersionRecord
     */
    public FeedVersionRecord() {
        super(FeedVersion.FEED_VERSION);
    }

    /**
     * Create a detached, initialised FeedVersionRecord
     */
    public FeedVersionRecord(String id, String feed, ULong timestamp, ULong size, String url, String start, String finish, Timestamp inserted) {
        super(FeedVersion.FEED_VERSION);

        set(0, id);
        set(1, feed);
        set(2, timestamp);
        set(3, size);
        set(4, url);
        set(5, start);
        set(6, finish);
        set(7, inserted);
    }
}
