/*
 * This file is generated by jOOQ.
 */
package com.schema.tables.records;


import com.schema.tables.Route;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record2;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RouteRecord extends UpdatableRecordImpl<RouteRecord> implements Record11<String, String, String, String, String, Byte, String, String, String, UInteger, String> {

    private static final long serialVersionUID = -1872135556;

    /**
     * Setter for <code>gtfs.route.route_id</code>.
     */
    public void setRouteId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gtfs.route.route_id</code>.
     */
    public String getRouteId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gtfs.route.agency_id</code>.
     */
    public void setAgencyId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gtfs.route.agency_id</code>.
     */
    public String getAgencyId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gtfs.route.default_name</code>. route_short_name
     */
    public void setDefaultName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gtfs.route.default_name</code>. route_short_name
     */
    public String getDefaultName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gtfs.route.route_long_name</code>.
     */
    public void setRouteLongName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gtfs.route.route_long_name</code>.
     */
    public String getRouteLongName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gtfs.route.route_desc</code>.
     */
    public void setRouteDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gtfs.route.route_desc</code>.
     */
    public String getRouteDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gtfs.route.route_type</code>.
     */
    public void setRouteType(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>gtfs.route.route_type</code>.
     */
    public Byte getRouteType() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>gtfs.route.route_url</code>.
     */
    public void setRouteUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gtfs.route.route_url</code>.
     */
    public String getRouteUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gtfs.route.route_color</code>.
     */
    public void setRouteColor(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gtfs.route.route_color</code>.
     */
    public String getRouteColor() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gtfs.route.route_text_color</code>.
     */
    public void setRouteTextColor(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gtfs.route.route_text_color</code>.
     */
    public String getRouteTextColor() {
        return (String) get(8);
    }

    /**
     * Setter for <code>gtfs.route.route_sort_order</code>.
     */
    public void setRouteSortOrder(UInteger value) {
        set(9, value);
    }

    /**
     * Getter for <code>gtfs.route.route_sort_order</code>.
     */
    public UInteger getRouteSortOrder() {
        return (UInteger) get(9);
    }

    /**
     * Setter for <code>gtfs.route.feed_version</code>.
     */
    public void setFeedVersion(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>gtfs.route.feed_version</code>.
     */
    public String getFeedVersion() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, Byte, String, String, String, UInteger, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, Byte, String, String, String, UInteger, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Route.ROUTE.ROUTE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Route.ROUTE.AGENCY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Route.ROUTE.DEFAULT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Route.ROUTE.ROUTE_LONG_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Route.ROUTE.ROUTE_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Route.ROUTE.ROUTE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Route.ROUTE.ROUTE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Route.ROUTE.ROUTE_COLOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Route.ROUTE.ROUTE_TEXT_COLOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field10() {
        return Route.ROUTE.ROUTE_SORT_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Route.ROUTE.FEED_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRouteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAgencyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDefaultName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRouteLongName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRouteDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getRouteType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRouteUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRouteColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getRouteTextColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component10() {
        return getRouteSortOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getFeedVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRouteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAgencyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDefaultName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRouteLongName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRouteDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getRouteType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRouteUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRouteColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRouteTextColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value10() {
        return getRouteSortOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFeedVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value1(String value) {
        setRouteId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value2(String value) {
        setAgencyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value3(String value) {
        setDefaultName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value4(String value) {
        setRouteLongName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value5(String value) {
        setRouteDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value6(Byte value) {
        setRouteType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value7(String value) {
        setRouteUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value8(String value) {
        setRouteColor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value9(String value) {
        setRouteTextColor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value10(UInteger value) {
        setRouteSortOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord value11(String value) {
        setFeedVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RouteRecord values(String value1, String value2, String value3, String value4, String value5, Byte value6, String value7, String value8, String value9, UInteger value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RouteRecord
     */
    public RouteRecord() {
        super(Route.ROUTE);
    }

    /**
     * Create a detached, initialised RouteRecord
     */
    public RouteRecord(String routeId, String agencyId, String defaultName, String routeLongName, String routeDesc, Byte routeType, String routeUrl, String routeColor, String routeTextColor, UInteger routeSortOrder, String feedVersion) {
        super(Route.ROUTE);

        set(0, routeId);
        set(1, agencyId);
        set(2, defaultName);
        set(3, routeLongName);
        set(4, routeDesc);
        set(5, routeType);
        set(6, routeUrl);
        set(7, routeColor);
        set(8, routeTextColor);
        set(9, routeSortOrder);
        set(10, feedVersion);
    }
}
