/*
 * This file is generated by jOOQ.
 */
package com.schema.tables.records;


import com.schema.tables.Service;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record2;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceRecord extends UpdatableRecordImpl<ServiceRecord> implements Record11<String, Byte, Byte, Byte, Byte, Byte, Byte, Byte, String, String, String> {

    private static final long serialVersionUID = -751827613;

    /**
     * Setter for <code>gtfs.service.service_id</code>. calendar.txt
     */
    public void setServiceId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gtfs.service.service_id</code>. calendar.txt
     */
    public String getServiceId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gtfs.service.monday</code>.
     */
    public void setMonday(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>gtfs.service.monday</code>.
     */
    public Byte getMonday() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>gtfs.service.tuesday</code>.
     */
    public void setTuesday(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>gtfs.service.tuesday</code>.
     */
    public Byte getTuesday() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>gtfs.service.wednesday</code>.
     */
    public void setWednesday(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>gtfs.service.wednesday</code>.
     */
    public Byte getWednesday() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>gtfs.service.thursday</code>.
     */
    public void setThursday(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>gtfs.service.thursday</code>.
     */
    public Byte getThursday() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>gtfs.service.friday</code>.
     */
    public void setFriday(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>gtfs.service.friday</code>.
     */
    public Byte getFriday() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>gtfs.service.saturday</code>.
     */
    public void setSaturday(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>gtfs.service.saturday</code>.
     */
    public Byte getSaturday() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>gtfs.service.sunday</code>.
     */
    public void setSunday(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>gtfs.service.sunday</code>.
     */
    public Byte getSunday() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>gtfs.service.start_date</code>.
     */
    public void setStartDate(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gtfs.service.start_date</code>.
     */
    public String getStartDate() {
        return (String) get(8);
    }

    /**
     * Setter for <code>gtfs.service.end_date</code>.
     */
    public void setEndDate(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>gtfs.service.end_date</code>.
     */
    public String getEndDate() {
        return (String) get(9);
    }

    /**
     * Setter for <code>gtfs.service.feed_version</code>.
     */
    public void setFeedVersion(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>gtfs.service.feed_version</code>.
     */
    public String getFeedVersion() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, Byte, Byte, Byte, Byte, Byte, Byte, Byte, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, Byte, Byte, Byte, Byte, Byte, Byte, Byte, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Service.SERVICE.SERVICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return Service.SERVICE.MONDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return Service.SERVICE.TUESDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Service.SERVICE.WEDNESDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Service.SERVICE.THURSDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Service.SERVICE.FRIDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Service.SERVICE.SATURDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Service.SERVICE.SUNDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Service.SERVICE.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Service.SERVICE.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Service.SERVICE.FEED_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getServiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component2() {
        return getMonday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getTuesday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getWednesday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getThursday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getFriday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getSaturday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getSunday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getFeedVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getServiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getMonday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getTuesday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getWednesday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getThursday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getFriday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getSaturday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getSunday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFeedVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value1(String value) {
        setServiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value2(Byte value) {
        setMonday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value3(Byte value) {
        setTuesday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value4(Byte value) {
        setWednesday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value5(Byte value) {
        setThursday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value6(Byte value) {
        setFriday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value7(Byte value) {
        setSaturday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value8(Byte value) {
        setSunday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value9(String value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value10(String value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord value11(String value) {
        setFeedVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServiceRecord values(String value1, Byte value2, Byte value3, Byte value4, Byte value5, Byte value6, Byte value7, Byte value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceRecord
     */
    public ServiceRecord() {
        super(Service.SERVICE);
    }

    /**
     * Create a detached, initialised ServiceRecord
     */
    public ServiceRecord(String serviceId, Byte monday, Byte tuesday, Byte wednesday, Byte thursday, Byte friday, Byte saturday, Byte sunday, String startDate, String endDate, String feedVersion) {
        super(Service.SERVICE);

        set(0, serviceId);
        set(1, monday);
        set(2, tuesday);
        set(3, wednesday);
        set(4, thursday);
        set(5, friday);
        set(6, saturday);
        set(7, sunday);
        set(8, startDate);
        set(9, endDate);
        set(10, feedVersion);
    }
}
