/*
 * This file is generated by jOOQ.
 */
package com.schema.tables.records;


import com.schema.tables.Stop;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StopRecord extends UpdatableRecordImpl<StopRecord> implements Record11<String, String, String, String, Double, Double, String, UByte, String, Byte, String> {

    private static final long serialVersionUID = -624987176;

    /**
     * Setter for <code>gtfs.stop.stop_id</code>.
     */
    public void setStopId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gtfs.stop.stop_id</code>.
     */
    public String getStopId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gtfs.stop.stop_code</code>.
     */
    public void setStopCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gtfs.stop.stop_code</code>.
     */
    public String getStopCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gtfs.stop.stop_name</code>.
     */
    public void setStopName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gtfs.stop.stop_name</code>.
     */
    public String getStopName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gtfs.stop.stop_desc</code>.
     */
    public void setStopDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gtfs.stop.stop_desc</code>.
     */
    public String getStopDesc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gtfs.stop.stop_lat</code>.
     */
    public void setStopLat(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>gtfs.stop.stop_lat</code>.
     */
    public Double getStopLat() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>gtfs.stop.stop_lon</code>.
     */
    public void setStopLon(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>gtfs.stop.stop_lon</code>.
     */
    public Double getStopLon() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>gtfs.stop.stop_url</code>.
     */
    public void setStopUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gtfs.stop.stop_url</code>.
     */
    public String getStopUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gtfs.stop.location_type</code>.
     */
    public void setLocationType(UByte value) {
        set(7, value);
    }

    /**
     * Getter for <code>gtfs.stop.location_type</code>.
     */
    public UByte getLocationType() {
        return (UByte) get(7);
    }

    /**
     * Setter for <code>gtfs.stop.parent_station</code>.
     */
    public void setParentStation(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gtfs.stop.parent_station</code>.
     */
    public String getParentStation() {
        return (String) get(8);
    }

    /**
     * Setter for <code>gtfs.stop.wheelchair_boarding</code>.
     */
    public void setWheelchairBoarding(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>gtfs.stop.wheelchair_boarding</code>.
     */
    public Byte getWheelchairBoarding() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>gtfs.stop.feed_version</code>.
     */
    public void setFeedVersion(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>gtfs.stop.feed_version</code>.
     */
    public String getFeedVersion() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, Double, Double, String, UByte, String, Byte, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, Double, Double, String, UByte, String, Byte, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Stop.STOP.STOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Stop.STOP.STOP_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Stop.STOP.STOP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Stop.STOP.STOP_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Stop.STOP.STOP_LAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Stop.STOP.STOP_LON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Stop.STOP.STOP_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field8() {
        return Stop.STOP.LOCATION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Stop.STOP.PARENT_STATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return Stop.STOP.WHEELCHAIR_BOARDING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Stop.STOP.FEED_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getStopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStopCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getStopName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStopDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getStopLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getStopLon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStopUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component8() {
        return getLocationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getParentStation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component10() {
        return getWheelchairBoarding();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getFeedVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getStopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStopCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStopName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStopDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getStopLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getStopLon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStopUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value8() {
        return getLocationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getParentStation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getWheelchairBoarding();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFeedVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value1(String value) {
        setStopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value2(String value) {
        setStopCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value3(String value) {
        setStopName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value4(String value) {
        setStopDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value5(Double value) {
        setStopLat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value6(Double value) {
        setStopLon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value7(String value) {
        setStopUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value8(UByte value) {
        setLocationType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value9(String value) {
        setParentStation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value10(Byte value) {
        setWheelchairBoarding(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord value11(String value) {
        setFeedVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StopRecord values(String value1, String value2, String value3, String value4, Double value5, Double value6, String value7, UByte value8, String value9, Byte value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StopRecord
     */
    public StopRecord() {
        super(Stop.STOP);
    }

    /**
     * Create a detached, initialised StopRecord
     */
    public StopRecord(String stopId, String stopCode, String stopName, String stopDesc, Double stopLat, Double stopLon, String stopUrl, UByte locationType, String parentStation, Byte wheelchairBoarding, String feedVersion) {
        super(Stop.STOP);

        set(0, stopId);
        set(1, stopCode);
        set(2, stopName);
        set(3, stopDesc);
        set(4, stopLat);
        set(5, stopLon);
        set(6, stopUrl);
        set(7, locationType);
        set(8, parentStation);
        set(9, wheelchairBoarding);
        set(10, feedVersion);
    }
}
