/*
 * This file is generated by jOOQ.
 */
package com.schema.tables.records;


import com.schema.tables.Trip;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record2;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TripRecord extends UpdatableRecordImpl<TripRecord> implements Record11<String, String, String, String, String, Byte, String, String, Byte, Byte, String> {

    private static final long serialVersionUID = 426935665;

    /**
     * Setter for <code>gtfs.trip.route_id</code>.
     */
    public void setRouteId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gtfs.trip.route_id</code>.
     */
    public String getRouteId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>gtfs.trip.service_id</code>.
     */
    public void setServiceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gtfs.trip.service_id</code>.
     */
    public String getServiceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gtfs.trip.trip_id</code>.
     */
    public void setTripId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gtfs.trip.trip_id</code>.
     */
    public String getTripId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gtfs.trip.trip_headsign</code>.
     */
    public void setTripHeadsign(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gtfs.trip.trip_headsign</code>.
     */
    public String getTripHeadsign() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gtfs.trip.trip_short_name</code>.
     */
    public void setTripShortName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gtfs.trip.trip_short_name</code>.
     */
    public String getTripShortName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gtfs.trip.direction_id</code>.
     */
    public void setDirectionId(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>gtfs.trip.direction_id</code>.
     */
    public Byte getDirectionId() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>gtfs.trip.block_id</code>.
     */
    public void setBlockId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gtfs.trip.block_id</code>.
     */
    public String getBlockId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gtfs.trip.shape_id</code>.
     */
    public void setShapeId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gtfs.trip.shape_id</code>.
     */
    public String getShapeId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gtfs.trip.wheelchair_accessible</code>.
     */
    public void setWheelchairAccessible(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>gtfs.trip.wheelchair_accessible</code>.
     */
    public Byte getWheelchairAccessible() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>gtfs.trip.bikes_allowed</code>.
     */
    public void setBikesAllowed(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>gtfs.trip.bikes_allowed</code>.
     */
    public Byte getBikesAllowed() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>gtfs.trip.feed_version</code>.
     */
    public void setFeedVersion(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>gtfs.trip.feed_version</code>.
     */
    public String getFeedVersion() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, Byte, String, String, Byte, Byte, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, Byte, String, String, Byte, Byte, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Trip.TRIP.ROUTE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Trip.TRIP.SERVICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Trip.TRIP.TRIP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Trip.TRIP.TRIP_HEADSIGN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Trip.TRIP.TRIP_SHORT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Trip.TRIP.DIRECTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Trip.TRIP.BLOCK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Trip.TRIP.SHAPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Trip.TRIP.WHEELCHAIR_ACCESSIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return Trip.TRIP.BIKES_ALLOWED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Trip.TRIP.FEED_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRouteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getServiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTripId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTripHeadsign();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTripShortName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getDirectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getBlockId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getShapeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getWheelchairAccessible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component10() {
        return getBikesAllowed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getFeedVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRouteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getServiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTripId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTripHeadsign();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTripShortName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getDirectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getBlockId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getShapeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getWheelchairAccessible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getBikesAllowed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFeedVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value1(String value) {
        setRouteId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value2(String value) {
        setServiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value3(String value) {
        setTripId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value4(String value) {
        setTripHeadsign(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value5(String value) {
        setTripShortName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value6(Byte value) {
        setDirectionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value7(String value) {
        setBlockId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value8(String value) {
        setShapeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value9(Byte value) {
        setWheelchairAccessible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value10(Byte value) {
        setBikesAllowed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord value11(String value) {
        setFeedVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TripRecord values(String value1, String value2, String value3, String value4, String value5, Byte value6, String value7, String value8, Byte value9, Byte value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TripRecord
     */
    public TripRecord() {
        super(Trip.TRIP);
    }

    /**
     * Create a detached, initialised TripRecord
     */
    public TripRecord(String routeId, String serviceId, String tripId, String tripHeadsign, String tripShortName, Byte directionId, String blockId, String shapeId, Byte wheelchairAccessible, Byte bikesAllowed, String feedVersion) {
        super(Trip.TRIP);

        set(0, routeId);
        set(1, serviceId);
        set(2, tripId);
        set(3, tripHeadsign);
        set(4, tripShortName);
        set(5, directionId);
        set(6, blockId);
        set(7, shapeId);
        set(8, wheelchairAccessible);
        set(9, bikesAllowed);
        set(10, feedVersion);
    }
}
