/*
 * This file is generated by jOOQ.
 */
package com.schema;


import com.schema.tables.Agency;
import com.schema.tables.Feed;
import com.schema.tables.FeedVersion;
import com.schema.tables.Frequency;
import com.schema.tables.Route;
import com.schema.tables.Service;
import com.schema.tables.ServiceException;
import com.schema.tables.Shape;
import com.schema.tables.Stop;
import com.schema.tables.StopTime;
import com.schema.tables.Trip;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gtfs extends SchemaImpl {

    private static final long serialVersionUID = -132377090;

    /**
     * The reference instance of <code>gtfs</code>
     */
    public static final Gtfs GTFS = new Gtfs();

    /**
     * The table <code>gtfs.agency</code>.
     */
    public final Agency AGENCY = com.schema.tables.Agency.AGENCY;

    /**
     * The table <code>gtfs.feed</code>.
     */
    public final Feed FEED = com.schema.tables.Feed.FEED;

    /**
     * The table <code>gtfs.feed_version</code>.
     */
    public final FeedVersion FEED_VERSION = com.schema.tables.FeedVersion.FEED_VERSION;

    /**
     * The table <code>gtfs.frequency</code>.
     */
    public final Frequency FREQUENCY = com.schema.tables.Frequency.FREQUENCY;

    /**
     * The table <code>gtfs.route</code>.
     */
    public final Route ROUTE = com.schema.tables.Route.ROUTE;

    /**
     * The table <code>gtfs.service</code>.
     */
    public final Service SERVICE = com.schema.tables.Service.SERVICE;

    /**
     * The table <code>gtfs.service_exception</code>.
     */
    public final ServiceException SERVICE_EXCEPTION = com.schema.tables.ServiceException.SERVICE_EXCEPTION;

    /**
     * The table <code>gtfs.shape</code>.
     */
    public final Shape SHAPE = com.schema.tables.Shape.SHAPE;

    /**
     * The table <code>gtfs.stop</code>.
     */
    public final Stop STOP = com.schema.tables.Stop.STOP;

    /**
     * The table <code>gtfs.stop_time</code>.
     */
    public final StopTime STOP_TIME = com.schema.tables.StopTime.STOP_TIME;

    /**
     * The table <code>gtfs.trip</code>.
     */
    public final Trip TRIP = com.schema.tables.Trip.TRIP;

    /**
     * No further instances allowed
     */
    private Gtfs() {
        super("gtfs", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Agency.AGENCY,
            Feed.FEED,
            FeedVersion.FEED_VERSION,
            Frequency.FREQUENCY,
            Route.ROUTE,
            Service.SERVICE,
            ServiceException.SERVICE_EXCEPTION,
            Shape.SHAPE,
            Stop.STOP,
            StopTime.STOP_TIME,
            Trip.TRIP);
    }
}
