/*
 * This file is generated by jOOQ.
 */
package com.schema;


import com.schema.tables.Agency;
import com.schema.tables.Feed;
import com.schema.tables.FeedVersion;
import com.schema.tables.Frequency;
import com.schema.tables.Route;
import com.schema.tables.Service;
import com.schema.tables.ServiceException;
import com.schema.tables.Shape;
import com.schema.tables.Stop;
import com.schema.tables.StopTime;
import com.schema.tables.Trip;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in gtfs
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>gtfs.agency</code>.
     */
    public static final Agency AGENCY = com.schema.tables.Agency.AGENCY;

    /**
     * The table <code>gtfs.feed</code>.
     */
    public static final Feed FEED = com.schema.tables.Feed.FEED;

    /**
     * The table <code>gtfs.feed_version</code>.
     */
    public static final FeedVersion FEED_VERSION = com.schema.tables.FeedVersion.FEED_VERSION;

    /**
     * The table <code>gtfs.frequency</code>.
     */
    public static final Frequency FREQUENCY = com.schema.tables.Frequency.FREQUENCY;

    /**
     * The table <code>gtfs.route</code>.
     */
    public static final Route ROUTE = com.schema.tables.Route.ROUTE;

    /**
     * The table <code>gtfs.service</code>.
     */
    public static final Service SERVICE = com.schema.tables.Service.SERVICE;

    /**
     * The table <code>gtfs.service_exception</code>.
     */
    public static final ServiceException SERVICE_EXCEPTION = com.schema.tables.ServiceException.SERVICE_EXCEPTION;

    /**
     * The table <code>gtfs.shape</code>.
     */
    public static final Shape SHAPE = com.schema.tables.Shape.SHAPE;

    /**
     * The table <code>gtfs.stop</code>.
     */
    public static final Stop STOP = com.schema.tables.Stop.STOP;

    /**
     * The table <code>gtfs.stop_time</code>.
     */
    public static final StopTime STOP_TIME = com.schema.tables.StopTime.STOP_TIME;

    /**
     * The table <code>gtfs.trip</code>.
     */
    public static final Trip TRIP = com.schema.tables.Trip.TRIP;
}
